### ISSUE TITLE
integrate the last 10sec of motion-sensor into float

### ISSUE THREAD

**Issue by ij0n** [c-base/c-flo#59]
take the last 10 seconds of boolean data from the motion sensors, convert all the boolean values to integers, calculate the average of the integer-list and output as float.
use this data  to draw graph in openmct.

this makes it look more like an "activity" sensor, because it gives out a float between 0 and 1 and not a boolean. also small jittery false-positives only show as a very small bump, while actual activity will look more like a constant 1

**Comment by bergie** [comment]
Maybe something like https://www.arduino.cc/en/Tutorial/Smoothing

**Comment by bergie** [comment]
Pretty erratic readings even with 10 second moving average

![screenshot 2017-07-15 at 02 21 15](https://user-images.githubusercontent.com/3346/28234813-4e74a816-6904-11e7-953c-edff1b25709a.png)

**Comment by bergie** [comment]
Note sure the results are materially better this way:

![screenshot 2017-07-18 at 15 09 09](https://user-images.githubusercontent.com/3346/28368275-1c26db3e-6c94-11e7-8921-790061b56bfe.png)

May have to investigate other problem spots:

* http://www.esp8266.com/viewtopic.php?f=13&t=2066
* https://www.reddit.com/r/arduino/comments/35v774/pir_sensor_rf_interference/

**Comment by bergie** [comment]
At Bitraf we also had false positives. There the fix was to have more space between the NodeMCU and the PIR sensor. Now the results from the laser room look quite plausible

![screenshot 2017-07-19 at 15 10 23](https://user-images.githubusercontent.com/3346/28368395-7d63bd72-6c94-11e7-9d2f-7f241457e7ff.png)
